packaging_format = 2

id = "mybb"
name = "MyBB"
description.en = "Forum software"
description.fr = "Forum open source et libre"

version = "1.8.39~ynh1"

maintainers = []

[upstream]
license = "LGPL-3.0-only"
website = "https://mybb.com/"
demo = "https://demomybb.tk/"
admindoc = "https://docs.mybb.com/1.8/administration/"
code = "https://github.com/mybb/mybb"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mybb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/mybb/mybb/releases/download/mybb_1839/mybb_1839.zip"
        sha256 = "04537bc28d924454dbbe6206962a122b3c5c20ffa3b94bec4f5c654a9d01c2cf"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        # This recreates the x.y.zz version number
        autoupdate.version_regex = "^mybb_([0-9])([0-9])([0-9])*$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.4-mysql, php8.4-xml"

    [resources.database]
    type = "mysql"
