packaging_format = 2

id = "mybb"
name = "MyBB"
description.en = "Forum software"
description.fr = "Forum open source et libre"

version = "1.8.31~ynh1"

maintainers = []

[upstream]
license = "LGPL-3.0-only"
website = "https://mybb.com/"
demo = "https://demomybb.tk/"
admindoc = "https://docs.mybb.com/1.8/administration/"
code = "https://github.com/mybb/mybb"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mybb"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/mybb/mybb/releases/download/mybb_1831/mybb_1831.zip"
        sha256 = "e88354f10893512ea8f426aff9d6a48f7e2cb20bd3988b001c59c9f29084c2f1"
        in_subdir = false

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.0-mysql, php8.0-xml"

    [resources.database]
    type = "mysql"
